#!/usr/bin/env zsh

successfully() {
  $* || (echo "\nfailed" 1>&2 && exit 1)
}

fancy_echo() {
  echo "\n$1"
}

if -f /etc/zshenv; then
  fancy_echo "Fixing OSX zsh environment bug ..."
    successfully sudo mv /etc/{zshenv,zshrc}
fi

fancy_echo "Installing Homebrew, a good OS X package manager ..."
  successfully ruby <(curl -fsS https://raw.github.com/mxcl/homebrew/go)
  successfully brew update

if ! grep -qs "recommended by brew doctor" ~/.zshrc; then
  fancy_echo "Put Homebrew location earlier in PATH ..."
    successfully echo "\n# recommended by brew doctor" >> ~/.zshrc
    successfully echo "export PATH='/usr/local/bin:$PATH'\n" >> ~/.zshrc
    successfully source ~/.zshrc
fi

fancy_echo "Installing The Silver Searcher (better than ack or grep) to search the contents of files ..."
  successfully brew install the_silver_searcher

fancy_echo "Installing ctags, to index files for vim tab completion of methods, classes, variables ..."
  successfully brew install ctags

fancy_echo "Installing tmux, to save project state and switch between projects ..."
  successfully brew install tmux

fancy_echo "Installing reattach-to-user-namespace, for copy-paste and RubyMotion compatibility with tmux ..."
  successfully brew install reattach-to-user-namespace

fancy_echo "Installing ImageMagick, to crop and resize images ..."
  successfully brew install imagemagick

fancy_echo "Installing QT, used by Capybara Webkit for headless Javascript integration testing ..."
  successfully brew install qt

fancy_echo "Installing watch, to execute a program periodically and show the output ..."
  successfully brew install watch
  
fancy_echo "Installing RVM, the better ruby/gem version manager ..."
  successfully curl -L https://get.rvm.io | bash -s stable

  source ~/.zshrc

fancy_echo "Installing ruby-build, to install Rubies ..."
  successfully brew install ruby-build

fancy_echo "Installing GNU Compiler Collection, a necessary prerequisite to installing Ruby ..."
  successfully brew tap homebrew/dupes
  successfully brew install apple-gcc42

fancy_echo "Updating to latest Rubygems version ..."
  successfully gem update --system

fancy_echo "Installing critical Ruby gems for Rails development ..."
  successfully gem install bundler foreman rails --no-document

fancy_echo "Installing GitHub CLI client ..."
  successfully curl http://hub.github.com/standalone -sLo ~/.bin/hub
  successfully chmod +x ~/.bin/hub

if ! grep -qs "DO NOT EDIT BELOW THIS LINE" ~/.zshrc; then
  fancy_echo "Prepare ~/.zshrc for http://github.com/thoughtbot/dotfiles ..."
    successfully echo "# DO NOT EDIT BELOW THIS LINE\n" >> ~/.zshrc
fi
